apiVersion: v1
kind: Pod
metadata:
  name: ameer-bash
spec:
  containers:
  - name: bash
    image: bash:latest
    command: [ "/usr/local/bin/bash", "-c", "--" ]    
    args: [ "while true; do sleep 30; done;" ]
    securityContext:
      capabilities:
          add: ["IPC_LOCK"]     
  tolerations:
  - key: "platform"
    operator: "Equal"
    value: "core01"
    effect: "NoSchedule"
